### ISSUE TITLE
An undefined error occurred while attempting to connect to the server. Status code 0: error.

### ISSUE THREAD

**Issue by alexvaccaro** [Microsoft/featuretimeline#2]
**Describe the bug**
On clicking "Feature Timeline" I get the error: "An undefined error occurred while attempting to connect to the server. Status code 0: error." in Chrome, and "'Promise' is undefined" when viweieng teh same page from IE11

**Browser**
Choose a browser
[x ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] VSTS
[x] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
Chrome:

![image](https://user-images.githubusercontent.com/3834213/39861331-2f613988-5438-11e8-9c19-ec50c2ed5da4.png)

IE 11

![image](https://user-images.githubusercontent.com/3834213/39861352-424e0b2a-5438-11e8-995a-15170a7214d5.png)

**Comment by navneet-g** [comment]
Can you upload fiddler trace? This could be related to network connectivity.

**Comment by navneet-g** [comment]
I have fixed IE11 issue related to 'Promise' is undefined

**Comment by timschps** [comment]
I seem te be having the same issue in MS edge when working with vsts:

An undefined error occurred while attempting to connect to the server. Status code 0: error.

**Comment by navneet-g** [comment]
Hi @timschps can you share Fiddler trace and any errors in Edge console?
Also does it repro in Chrome for you?

**Comment by alexvaccaro** [comment]
Hi @navneet-g , 

My TFS server is on the same network and my proxy settings are set to bypass local addresses. I have also added my TFS url to the exclusions list but the problem still persists.

Looking at the Fiddler logs there are a couple of 404 responses for these calls:

```
GET /tfs/BCN/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/Default/Current/Collections/%24settings/Documents/overriddenWorkItemIterations HTTP/1.1

GET /tfs/BCN/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/ae288b25-ed21-491a-8ca2-333bbc0b274a_iterationDisplayOptions HTTP/1.1
```

On the other hand the "Promise" message in IE has been replaced by teh same error message I get in Chrome, so I suppose that issue has been fixed.

**Comment by JaccoRademaker** [comment]
Yesterday I had this same issue "Status code 0: error" on VSTS, but did not get to using Fiddler.
Today I am able to load the timeline, for me the issue has been resolved.
Keep up the good work, this extension is really helpful.

**Comment by alexvaccaro** [comment]
I tried again on my local TFS server and now is working, I believe the extension was automatically updated with the latest changes.

**Comment by navneet-g** [comment]
Great ... I did not make any changes for this as it is related to network. Th 404s are expected as there are no user specific settings available on first use. I am closing the issue.

**Comment by ChanakaThilakarathna** [comment]
Disable chrome extension related to Allow CORS : Access-Control-Allow-Origin fix my issue
