### ISSUE TITLE
Epic Roadmap (Beta) doesn't load

### ISSUE THREAD

**Issue by MichaelHarmsen** [microsoft/featuretimeline#28]
**Describe the bug**
When I click the "Epic Roadmap (Beta)" link, the page just says Loading... and never finishes. The Feature Timeline works fine.

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] VSTS
[x] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/25432105/43455974-ffe98258-94c1-11e8-8c01-e65c0470f843.png)

**Comment by navneetg-msft** [comment]
Thanks for reporting ... do you see any errors in Chrome console?

**Comment by navneetg-msft** [comment]
I have published an update, can you retry.

**Comment by MichaelHarmsen** [comment]
Hi

I've tried the new version but get the same result. In the Chrome console I
can see this exception:

"uncaught at FetchAllMetadata at FetchAllMetadata
 at FetchAllMetadata
 TFS.WebApi.Exception: TF400813: Resource not available for anonymous
access. Client authentication required."

Does this help narrowing it down?

Let me know if you need more details from the console.

Cheers, Michael

**Comment by navneetg-msft** [comment]
This error is interesting “Resource not available for anonymous
access. Client authentication required”

Are you logged in to VSTS? Can you try using the extension in incognito?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MichaelHarmsen** [comment]
Hi

No, I am not logged in to VSTS. I am running the extension on-premise on
TFS 2017 Update 2.

I tried the extension in a Chrome incognito tab and got the same result.

Cheers Michael

**Comment by dcasbonne** [comment]
Hello,

Same config here and same problem. It didn't load with the same error message. Hope you can find a solution !

**Comment by navneetg-msft** [comment]
This is interesting if this is TFS 2017. Can we setup a call to live debug? You can send me an email at navneetg at microsoft.com

**Comment by dcasbonne** [comment]
Yes, TFS2017, I've sent you an email for the detail of the debugging session ;)

**Comment by riaank** [comment]
Hi.  I am having the same issue in TFS 2017.  My Future Timeline is also not working?

**Comment by navneet-g** [comment]
I just pushed an update, that should partially fix it, can you try it out and let me know what you see now.

**Comment by riaank** [comment]
Hi navneet-g.  The Feature Timeline is working now.  Thanks!  However, the Epic Roadmap is still giving issues in Chrome.

Here are the error messages:

Failed to load resource: the server responded with a status of 401 (Unauthorized)
/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/EpicRoadmapa89a2e34-fcb9-4773-9491-ea2156de0e51_settings:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/EpicRoadmapa89a2e34-fcb9-4773-9491-ea2156de0e51_iterationDisplayOptions:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/040b01d6-50ec-45d9-a2c1-b7b39da2d62d/_apis/work/backlogconfiguration:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
utils.js:225 uncaught at FetchAllMetadata at FetchAllMetadata 
 at FetchAllMetadata 
 TFS.WebApi.Exception: TF400813: Resource not available for anonymous access. Client authentication required.

**Comment by navneetg-msft** [comment]
For TFS 2017, someone was able to resolve it by restarting the server. Can you try that?

**Comment by riaank** [comment]
Hi Navneetg

Restarted the server but still getting the following error message when I click on Epic Roadmap.

Failed to load resource: the server responded with a status of 401 (Unauthorized)
utils.js:225 uncaught at FetchAllMetadata at FetchAllMetadata 
 at FetchAllMetadata 
 TFS.WebApi.Exception: TF400813: Resource not available for anonymous access. Client authentication required.

**Comment by MichaelHarmsen** [comment]
Same here: the servers have been rebooted since installing the extension
and it made no difference.

Cheers Michael

**Comment by burtonrodman** [comment]
I am having this issue also.  TFS 2017 Update 3.

**Comment by LeonardTr** [comment]
We have the same issue with TFS 2017 Update 2

**Comment by AnReZa** [comment]
We are also affected by this bug.

**Comment by frackham** [comment]
Same here, on prem Version 15.117.26714.0.

**Comment by rachelr1977** [comment]
I am having the same issue - Version 15.117.27024.0, also on-premises version.

**Comment by Rickm1970** [comment]
I am also having this issue. Version 15.117.27024.0, also on-premises version.

**Comment by dotcologne** [comment]
Pretty proven, this is a permission issue. When I'm logged in as Azure superadmin, it works like a charm. But when I use another (Co-Admin) account, I get this error. Attached the relevant captured RQs/RSs from Fiddler.
[rq1.txt](https://github.com/microsoft/featuretimeline/files/3977545/rq1.txt)
[rq2.txt](https://github.com/microsoft/featuretimeline/files/3977546/rq2.txt)
[rs1.txt](https://github.com/microsoft/featuretimeline/files/3977548/rs1.txt)
[rs2.txt](https://github.com/microsoft/featuretimeline/files/3977549/rs2.txt)

**Comment by nareshkumarhk** [comment]
Same issue, is there any ETA for this bug
